version: "3.5"

networks:
  container-link:
    driver: bridge

services:
  db:
    container_name: postgres-db
    env_file: ./db/.env
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    ports:
      - 15432:5432
    networks:
      - container-link
